version: '3'
services:
    web:
        image: nginx:1.22-alpine
        ports:
            - "8083:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app

    php:
        build:
            context: .
        volumes:
            - ./app:/app